# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vinyl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255)),
                ('artist', models.IntegerField()),
                ('description', models.TextField(max_length=255)),
                ('picture', models.FileField(upload_to='vinyl/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
