# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinyl_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinyl',
            name='artist',
            field=models.TextField(max_length=255),
        ),
    ]
