# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinyl_app', '0002_auto_20171213_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinyl',
            name='price',
            field=models.TextField(default='', max_length=8),
            preserve_default=False,
        ),
    ]
